[workspace]
members = [
    "crates/oddutils-core",
    "crates/chronic",
    "crates/errno",
    "crates/ifne",
    "crates/isutf8",
    "crates/mispipe",
    "crates/pee",
    "crates/sponge",
    "crates/ts",
    "crates/vidir",
    "crates/vipe",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
