name: BSD

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Test on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.4"
          usesh: true
          prepare: |
            pkg install -y rust scdoc
          run: |
            cargo test
            cargo build --release

  openbsd:
    name: OpenBSD
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.8"
          usesh: true
          prepare: |
            pkg_add rust scdoc
          run: |
            cargo test
            cargo build --release
